### PR TITLE
add FFFit_vote.md and cemo_vote.md in votes/

### PR DESCRIPTION
**Pull request by yuhangwang**
I would like to add two open-source projects (cemo and FFFit) to DeepModeling.

### CODE REVIEW

**Comment by likefallwind** [comment]
Hi, would you please add more description about your projects? Just as other projects in deepmodeling. You can write it in README file. Otherwise people may don't know what this project is.

**Comment by wanghan-iapcm** [comment]
+1

**Comment by likefallwind** [comment]
# A vote for community Logo: FFFit

## Proposal
`FFFit` is a Python package that implements the Fragment-guided Flexible Fitting algorithm (FFF), which was published at the CVPR23 conference (https://ieeexplore.ieee.org/document/10204035).


## Deadline
The vote will be open for at least 7 days unless there is an objection.

## Scope
TOC members

**Comment by likefallwind** [comment]
# A vote for community Logo: cemo

## Proposal
`cemo` is a python library designed for facilitating building
applications for cryo-EM 3D reconstruction tasks. Many functions/modules are written using pyTorch, making it easier to implement
machine-learning-based cryo-EM algorithms.

## Deadline
The vote will be open for at least 7 days unless there is an objection.

## Scope
TOC members

**Pull request merged**
