### PR TITLE
Add a vote for a new project: fpop

### PR DESCRIPTION
**Pull request by AnguseZhang**

### CODE REVIEW

**Comment by wanghan-iapcm** [comment]
+1

**Comment by zjgemi** [comment]
+1

**Comment by likefallwind** [comment]
# A Vote for New Projects: fpop

## Proposal


We propose to create a repository to host standardized and reusable first-principles calculations operators, based on dflow.


## Deadline

The vote will be open for at least 3 days unless there is an objection.（Because a website depends on this repo is very urgent, so we change the vote time )

## Scope

TOC MEMBERS.

**Comment by likefallwind** [comment]
The project is urgent, so I make the repo now. If there is an objection, I'll delete that repo.

**Pull request merged**
