### PR TITLE
Add a vote for a new project: alloytest

### PR DESCRIPTION
**Pull request by kevinwenminion**

### CODE REVIEW

**Review by zjgemi — APPROVED** [review]

**Comment by likefallwind** [comment]
Is it very urgent？
If not, out vote may last for at least 7 days

**Comment by AnguseZhang** [comment]
@wanghan-iapcm @jameswind Could you please have a look?  @kevinwenminion needs a repo, and then makes PRs to this new repo, to promote the development of the workflow for alloy property prediction.

Other optional names include `MAPS: Modeling Alloy Properties using Simulations` or  `APEX: Alloy Properties EXplorer using simulations`.

**Comment by wanghan-iapcm** [comment]
+1

**Comment by jameswind** [comment]
+1

**Pull request merged**
