### PR TITLE
A Vote for New Projects: ReacNetGenerator

### PR DESCRIPTION
**Pull request by njzjz**
# A Vote for New Projects: ReacNetGenerator

## Proposal

[ReacNetGenerator](https://github.com/tongzhugroup/reacnetgenerator) is an automatic reaction network generator for reactive molecular dynamics simulation. Initially published in 2020 \[[Phys. Chem. Chem. Phys., 2020, 22 (2): 683–691](https://doi.org/10.1039/C9CP05091D)\], it has been [cited 61 times](https://scholar.google.com/scholar?cites=11110115133859772670), [used in 34 research articles](https://njzjz.win/reacnetgenerator/), and [starred by 52 GitHub users](https://github.com/tongzhugroup/reacnetgenerator/stargazers).

## Deadline

Feb 12, 2024

## Scope

TOC MEMBERS.

----

Initially proposed by Linfeng @jameswind and Tong @z5476t4508.

### CODE REVIEW

**Comment by wanghan-iapcm** [comment]
+1

**Comment by jameswind** [comment]
+1

**Comment by z5476t4508** [comment]
+1

jameswind ***@***.***> 于2024年2月6日周二 13:50写道：

> +1
>

**Comment by zhixchen** [comment]
+1

**Pull request merged**
