### PR TITLE
Add a Vote for New Projects: AIS-Square

### PR DESCRIPTION
**Pull request by iProzd**
The development of scientific computing has been rapidly boosted by machine learning and other methods in the past few years. Recent methods, such as [DPA-1](https://arxiv.org/abs/2208.08236), has brought us to a new stage, where approaches in Computer Vision (CV) or Natural Language Processing (NLP), such as pre-training, fine-tuning or transfer learning, can be directly utilized in scientific modeling. This will save huge computational cost for model training and obtain more unified models, being the future of scientific computing. Here we come to a point where an easy-to-use, quickly-updated and unified platform is needed for gathering the existing datasets, trained models or workflows to amplify this trend, similar to [Hugging Face website](https://huggingface.co/) in NLP field.

Here we propose AIS-Square, a unified platform for users to download/upload the datasets, models or workflows for scientific computing. AI stands for both ab initio and Artificial Intelligence here, thus we use S, second power or square, for this pun. On the other hand, Square also means this unified platform gathering wisdom and sharing contributions. This repo will be the backend for AIS-Square website, storing items information (README and download links) uploaded by contributors. And The website will be updated according to this repo every minutes. A standard PR format will be added in this repo, so maintainers can review each item before it appears on the website.

### CODE REVIEW

**Comment by iProzd** [comment]
Little spark, deep flame!

**Review by zjgemi — APPROVED** [review]

**Comment by jameswind** [comment]
+1

**Comment by zhixchen** [comment]
+1

**Comment by wanghan-iapcm** [comment]
+1

**Comment by KuangYu** [comment]
+1

**Pull request merged**
