### PR TITLE
vote for the modify of governance rules

### PR DESCRIPTION
**Pull request by likefallwind**

### CODE REVIEW

**Comment by likefallwind** [comment]
# A vote for modify the rules of deepmodeling governance

## Proposal

### Objective: 

To create a more efficient and flexible decision-making process within the DeepModeling Community by updating the Lazy Consensus and Majority Vote rules.

### Background: 

The current decision-making rules in the DeepModeling Community are Lazy Consensus and Majority Vote. While these rules have been effective in the past, there is room for improvement to make the decision-making process more efficient, especially in urgent situations.

### Proposed Changes:

1. Lazy Consensus: A proposal is considered supported by the community as long as nobody objects. This is the default decision-making mechanism in the DeepModeling Community, inspired by Apache Lazy Consensus. In cases of an objection, and no consensus can be found, a majority vote will be held. If a participant who makes a vote is in an urgent situation, they can request to change the Lazy Consensus process to a Majority Vote process to accelerate the decision-making.

2. Majority Vote: A majority vote is compelled in a separate pull request when there is no lazy consensus or when requested by a participant in an urgent situation, and requires a 2/3 majority to pass. If 2/3 majority is reached before the voting deadline, the proposal will be passed directly. If the requirement is not met until the voting deadline, there will be a meeting to discuss the topic, followed by another compulsory majority vote.

### Rationale: 

By allowing participants in urgent situations to request a change from Lazy Consensus to Majority Vote, we can speed up the decision-making process when necessary without sacrificing the overall collaborative nature of the community. Additionally, passing a proposal directly when a 2/3 majority is reached before the voting deadline in Majority Vote situations will help streamline the decision-making process. These changes will lead to a more efficient and flexible decision-making system within the DeepModeling Community.

We kindly request the TOC members to review these proposed changes and provide their feedback. If the majority approves the changes, we will update the decision-making rules accordingly.

**Comment by wanghan-iapcm** [comment]
+1

**Comment by zjgemi** [comment]
+1

**Comment by mohanchen** [comment]
+1

**Comment by jameswind** [comment]
+1

**Comment by KuangYu** [comment]
+1

**Comment by zhixchen** [comment]
+1

**Pull request merged**
