### PR TITLE
Add a Vote for New Projects: DeepH-pack

### PR DESCRIPTION
**Pull request by mzjb**

### CODE REVIEW

**Comment by wanghan-iapcm** [comment]
@mzjb Could you please add a short description of the DeePH project? and the link to the source code if any.

**Comment by mzjb** [comment]
> @mzjb Could you please add a short description of the DeePH project? and the link to the source code if any.

A short desciption and the source code of the DeepH project could be found the newly added file [DeepH_vote.md](https://github.com/deepmodeling/community/pull/12/files#diff-394799a03ad0a090e84be0f51843c8d9267e8a832a7ffdbdecfd7c050bc9441b). Below is the content of the file `DeepH_vote.md`:

DeepH-pack is the official implementation of the Deep Hamiltonian (DeepH) method described in the paper [*Deep-learning density functional theory Hamiltonian for efficient ab initio electronic-structure calculation*](https://www.nature.com/articles/s43588-022-00265-6) and in the [Research Briefing](https://www.nature.com/articles/s43588-022-00270-9). For more information, see the [documentation](https://deeph-pack.readthedocs.io) and the [original repository](https://github.com/mzjb/DeepH-pack).

DeepH method employs a graph neural network to represent the mapping from the atomic structure of a material to the density functional theory (DFT) Hamiltonian, from which all the electronic-related physical quantities in the single-particle picture can be predicted, including the band structure, Berry phase and physical responses to external fields. Importantly, DeepH takes full advantage of the 'nearsightedness' principle of electronic matter and can properly deal with covariance (i.e. equivariance) of the Hamiltonian matrix by basis transformation, which ensures good generalizability. By learning from DFT and then making independent predictions, DeepH can bypass the computationally most demanding part of a DFT simulation (namely the self-consistent field iterations) and, thus, substantially improve the efficiency of ab initio electronic-structure calculations and greatly extend the scope of first-principles materials research.

**Comment by mohanchen** [comment]
+1

**Comment by jameswind** [comment]
+1

**Comment by wanghan-iapcm** [comment]
+1

**Comment by zhixchen** [comment]
+1

**Pull request merged**
