### PR TITLE
Create JAX-FEM_vote

### PR DESCRIPTION
**Pull request by RussellHu41**
Create a vote for JAX-FEM.

### CODE REVIEW

**Comment by likefallwind** [comment]
# A Vote for New Projects:  JAX-FEM

## Proposal

JAX-FEM is a GPU-accelerated differentiable finite element analysis package based on JAX. Used to be part of the suite of open-source python packages for Additive Manufacturing (AM) research, JAX-AM.
- JAX-FEM now support multi-physics problems in the sense that multiple variables can be solved monolithically. 
- Weak form is now defined through volume integral and surface integral. JAX-FEM can now treat body force, "mass kernel" and "Laplace kernel" in a unified way through volume integral, and treat "Neumann B.C." and "Robin B.C." in a unified way through surface integral.
For more information, see the [original repository](https://github.com/tianjuxue/jax-fem)

## Deadline

The vote will be open for at least 6 days unless there is an objection.

## Scope

TOC MEMBERS.

**Comment by mohanchen** [comment]
+1

**Comment by iProzd** [comment]
+1

**Comment by zhixchen** [comment]
+1

**Comment by wanghan-iapcm** [comment]
+1

**Comment by jameswind** [comment]
+1

**Comment by KuangYu** [comment]
+1

**Pull request merged**
